cat "dependencies/bootstrap-notify.min.js" > script.js
echo "" >> script.js
cat "dependencies/socket.io.js" >> script.js
echo "" >> script.js
cat "declare.js" >> script.js
echo "" >> script.js
cat "sync.js" >> script.js
echo "" >> script.js
cat "player.js" >> script.js
echo "" >> script.js
cat "host.js" >> script.js
echo "" >> script.js
cat "events.js" >> script.js
echo "" >> script.js
cat "notify.js" >> script.js
echo "" >> script.js
cat "jwplayer.js" >> script.js
echo "" >> script.js
cat "transmission.js" >> script.js
echo "" >> script.js
echo "undefined;" >> script.js
echo "" >> script.js